AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VPCTenancy:
    Type: "String"
    Default: "default"
    AllowedValues:
      - default
      - dedicated
    Description: "Enter Dedicated or Default. Default is Default."

Resources:
  myVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "172.15.0.0/16"
      EnableDnsSupport: false
      EnableDnsHostnames: false
      InstanceTenancy: !Ref VPCTenancy
      Tags:
        - Key: "foo"
          Value: "bar"